// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: assistant.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The greeting request message with the user's name and institution.
type GreetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"` // user's name at the 1st position
	Institution   string                 `protobuf:"bytes,2,opt,name=institution,proto3" json:"institution,omitempty"`           // user's institution at the 2nd position
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetRequest) Reset() {
	*x = GreetRequest{}
	mi := &file_assistant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetRequest) ProtoMessage() {}

func (x *GreetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetRequest.ProtoReflect.Descriptor instead.
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{0}
}

func (x *GreetRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *GreetRequest) GetInstitution() string {
	if x != nil {
		return x.Institution
	}
	return ""
}

// The greeting response message with the constructed message.
type GreetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetResponse) Reset() {
	*x = GreetResponse{}
	mi := &file_assistant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetResponse) ProtoMessage() {}

func (x *GreetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetResponse.ProtoReflect.Descriptor instead.
func (*GreetResponse) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{1}
}

func (x *GreetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// The multiplication request message including two input double numbers.
type MultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Xin           float64                `protobuf:"fixed64,1,opt,name=xin,proto3" json:"xin,omitempty"`
	Yin           float64                `protobuf:"fixed64,2,opt,name=yin,proto3" json:"yin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultRequest) Reset() {
	*x = MultRequest{}
	mi := &file_assistant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultRequest) ProtoMessage() {}

func (x *MultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultRequest.ProtoReflect.Descriptor instead.
func (*MultRequest) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{2}
}

func (x *MultRequest) GetXin() float64 {
	if x != nil {
		return x.Xin
	}
	return 0
}

func (x *MultRequest) GetYin() float64 {
	if x != nil {
		return x.Yin
	}
	return 0
}

// The multiplication response message including the inputs and the output number.
type MultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Xin           float64                `protobuf:"fixed64,1,opt,name=xin,proto3" json:"xin,omitempty"`
	Yin           float64                `protobuf:"fixed64,2,opt,name=yin,proto3" json:"yin,omitempty"`
	Result        float64                `protobuf:"fixed64,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultResponse) Reset() {
	*x = MultResponse{}
	mi := &file_assistant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultResponse) ProtoMessage() {}

func (x *MultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assistant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultResponse.ProtoReflect.Descriptor instead.
func (*MultResponse) Descriptor() ([]byte, []int) {
	return file_assistant_proto_rawDescGZIP(), []int{3}
}

func (x *MultResponse) GetXin() float64 {
	if x != nil {
		return x.Xin
	}
	return 0
}

func (x *MultResponse) GetYin() float64 {
	if x != nil {
		return x.Yin
	}
	return 0
}

func (x *MultResponse) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_assistant_proto protoreflect.FileDescriptor

const file_assistant_proto_rawDesc = "" +
	"\n" +
	"\x0fassistant.proto\"M\n" +
	"\fGreetRequest\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12 \n" +
	"\vinstitution\x18\x02 \x01(\tR\vinstitution\")\n" +
	"\rGreetResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"1\n" +
	"\vMultRequest\x12\x10\n" +
	"\x03xin\x18\x01 \x01(\x01R\x03xin\x12\x10\n" +
	"\x03yin\x18\x02 \x01(\x01R\x03yin\"J\n" +
	"\fMultResponse\x12\x10\n" +
	"\x03xin\x18\x01 \x01(\x01R\x03xin\x12\x10\n" +
	"\x03yin\x18\x02 \x01(\x01R\x03yin\x12\x16\n" +
	"\x06result\x18\x03 \x01(\x01R\x06result2k\n" +
	"\x10AssistantService\x12.\n" +
	"\rGreetWithInfo\x12\r.GreetRequest\x1a\x0e.GreetResponse\x12'\n" +
	"\bMultiply\x12\f.MultRequest\x1a\r.MultResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_assistant_proto_rawDescOnce sync.Once
	file_assistant_proto_rawDescData []byte
)

func file_assistant_proto_rawDescGZIP() []byte {
	file_assistant_proto_rawDescOnce.Do(func() {
		file_assistant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assistant_proto_rawDesc), len(file_assistant_proto_rawDesc)))
	})
	return file_assistant_proto_rawDescData
}

var file_assistant_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_assistant_proto_goTypes = []any{
	(*GreetRequest)(nil),  // 0: GreetRequest
	(*GreetResponse)(nil), // 1: GreetResponse
	(*MultRequest)(nil),   // 2: MultRequest
	(*MultResponse)(nil),  // 3: MultResponse
}
var file_assistant_proto_depIdxs = []int32{
	0, // 0: AssistantService.GreetWithInfo:input_type -> GreetRequest
	2, // 1: AssistantService.Multiply:input_type -> MultRequest
	1, // 2: AssistantService.GreetWithInfo:output_type -> GreetResponse
	3, // 3: AssistantService.Multiply:output_type -> MultResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_assistant_proto_init() }
func file_assistant_proto_init() {
	if File_assistant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assistant_proto_rawDesc), len(file_assistant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_assistant_proto_goTypes,
		DependencyIndexes: file_assistant_proto_depIdxs,
		MessageInfos:      file_assistant_proto_msgTypes,
	}.Build()
	File_assistant_proto = out.File
	file_assistant_proto_goTypes = nil
	file_assistant_proto_depIdxs = nil
}
