# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import assistant_pb2 as assistant__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in assistant_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AssistantServiceStub(object):
    """Stlye Guide: https://protobuf.dev/programming-guides/style/.
    Files should be named `lower_snake_case.proto`.


    Services are what the servers provide for the clients. Specifically for gRPC.
    Use PascalCase (with an initial capital) for both the service name and any RPC method names.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChillA = channel.unary_unary(
                '/AssistantService/ChillA',
                request_serializer=assistant__pb2.ChatMessage.SerializeToString,
                response_deserializer=assistant__pb2.ChatMessage.FromString,
                _registered_method=True)
        self.ChillB = channel.unary_unary(
                '/AssistantService/ChillB',
                request_serializer=assistant__pb2.ChatMessage.SerializeToString,
                response_deserializer=assistant__pb2.ChatMessage.FromString,
                _registered_method=True)


class AssistantServiceServicer(object):
    """Stlye Guide: https://protobuf.dev/programming-guides/style/.
    Files should be named `lower_snake_case.proto`.


    Services are what the servers provide for the clients. Specifically for gRPC.
    Use PascalCase (with an initial capital) for both the service name and any RPC method names.
    """

    def ChillA(self, request, context):
        """2 Chilling functions that sleep for a while.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChillB(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AssistantServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChillA': grpc.unary_unary_rpc_method_handler(
                    servicer.ChillA,
                    request_deserializer=assistant__pb2.ChatMessage.FromString,
                    response_serializer=assistant__pb2.ChatMessage.SerializeToString,
            ),
            'ChillB': grpc.unary_unary_rpc_method_handler(
                    servicer.ChillB,
                    request_deserializer=assistant__pb2.ChatMessage.FromString,
                    response_serializer=assistant__pb2.ChatMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AssistantService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('AssistantService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AssistantService(object):
    """Stlye Guide: https://protobuf.dev/programming-guides/style/.
    Files should be named `lower_snake_case.proto`.


    Services are what the servers provide for the clients. Specifically for gRPC.
    Use PascalCase (with an initial capital) for both the service name and any RPC method names.
    """

    @staticmethod
    def ChillA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AssistantService/ChillA',
            assistant__pb2.ChatMessage.SerializeToString,
            assistant__pb2.ChatMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChillB(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AssistantService/ChillB',
            assistant__pb2.ChatMessage.SerializeToString,
            assistant__pb2.ChatMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
