[project]
name = "hello-world"
version = "0.1.0"
description = "Implementing a simple RESTful API server using Python Flask."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask==3.0.3",
    "requests==2.32.3",
]
