# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import assistant_pb2 as assistant__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in assistant_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AssistantServiceStub(object):
    """python -m grpc_tools.protoc -I./ --python_out=. --pyi_out=. --grpc_python_out=. assistant.proto

    Stlye Guide: https://protobuf.dev/programming-guides/style/.
    Files should be named `lower_snake_case.proto`.


    Services are what the servers provide for the clients. Specifically for gRPC.
    Use PascalCase (with an initial capital) for both the service name and any RPC method names.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportStats = channel.unary_unary(
                '/AssistantService/ReportStats',
                request_serializer=assistant__pb2.ReportStatsRequest.SerializeToString,
                response_deserializer=assistant__pb2.ReportStatsResponse.FromString,
                _registered_method=True)


class AssistantServiceServicer(object):
    """python -m grpc_tools.protoc -I./ --python_out=. --pyi_out=. --grpc_python_out=. assistant.proto

    Stlye Guide: https://protobuf.dev/programming-guides/style/.
    Files should be named `lower_snake_case.proto`.


    Services are what the servers provide for the clients. Specifically for gRPC.
    Use PascalCase (with an initial capital) for both the service name and any RPC method names.
    """

    def ReportStats(self, request, context):
        """Calculates the min, max, avg of the provided numeric values, and gives a response in natural language.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AssistantServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportStats': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportStats,
                    request_deserializer=assistant__pb2.ReportStatsRequest.FromString,
                    response_serializer=assistant__pb2.ReportStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AssistantService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('AssistantService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AssistantService(object):
    """python -m grpc_tools.protoc -I./ --python_out=. --pyi_out=. --grpc_python_out=. assistant.proto

    Stlye Guide: https://protobuf.dev/programming-guides/style/.
    Files should be named `lower_snake_case.proto`.


    Services are what the servers provide for the clients. Specifically for gRPC.
    Use PascalCase (with an initial capital) for both the service name and any RPC method names.
    """

    @staticmethod
    def ReportStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AssistantService/ReportStats',
            assistant__pb2.ReportStatsRequest.SerializeToString,
            assistant__pb2.ReportStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
