# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: assistant.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'assistant.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61ssistant.proto\"L\n\x12ReportStatsRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x13\n\x0binstitution\x18\x02 \x01(\t\x12\x0e\n\x06values\x18\x03 \x03(\x01\"_\n\x13ReportStatsResponse\x12\x11\n\tmin_value\x18\x01 \x01(\x01\x12\x11\n\tmax_value\x18\x02 \x01(\x01\x12\x11\n\tavg_value\x18\x03 \x01(\x01\x12\x0f\n\x07message\x18\x04 \x01(\t2L\n\x10\x41ssistantService\x12\x38\n\x0bReportStats\x12\x13.ReportStatsRequest\x1a\x14.ReportStatsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'assistant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REPORTSTATSREQUEST']._serialized_start=19
  _globals['_REPORTSTATSREQUEST']._serialized_end=95
  _globals['_REPORTSTATSRESPONSE']._serialized_start=97
  _globals['_REPORTSTATSRESPONSE']._serialized_end=192
  _globals['_ASSISTANTSERVICE']._serialized_start=194
  _globals['_ASSISTANTSERVICE']._serialized_end=270
# @@protoc_insertion_point(module_scope)
